[platformio]
default_envs = esp32-cyd

[env:esp32-cyd]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
  bblanchon/ArduinoJson@^7.0.4
  adafruit/Adafruit NeoPixel@^1.12.3
build_flags =
  -D USER_SETUP_LOADED=1
  -include include/User_Setup.h
build_src_filter =
  +<main.cpp>
